### ISSUE TITLE
Update Translate zh-CN

### ISSUE THREAD

**Issue by XHXIAIEIN** [wsdo/gptapi#3]
提供给一个看上去好一点的中文翻译内容

## 初始引导

| English           | 简体中文 |
| ----------------- | -------- |
| This is a free research preview. | 这是一项免费的研究项目，目前仍在测试阶段。 | 
| Our goal is to get external feedback in order to improve our systems and make them safer. | 我们的目标是获得公众的反馈，以改进我们的对话系统，使其更加安全。 | 
| While we have safeguards in place, the system may occasionally generate incorrect or misleading information and produce offensive or biased content. It is not intended to give advice. | 虽然我们对内容提供了一定的保障措施，但对话系统仍然可能会产生一些不正确或误导性的信息，甚至包含攻击性或带有偏见的内容，它们不能作为真正的建议参考。 | 
| How we collect data |  我们如何收集数据？ | 
| Conversations may be reviewed by our AI trainers to improve our systems. | 你的对话可能会被我们的人工智能培训师审查，以改善我们的系统。 | 
| Please don't share any sensitive information in your conversations. | 请不要在对话中分享任何敏感信息，如真实姓名、手机号、邮箱、地理位置等。 | 
| This system is optimized for dialogue. Let us know if a particular response was good or unhelpful.| 对话页面设计了评价系统，它可以帮助我们优化对话系统。如果你认为对话的回应是正确的或是毫不相关的，请务必让我们知道。  | 
| Share your feedback in our Discord server. | 或可以加入 ChatGPT 官方 [Discord 服务器](https://discord.com/invite/openai) 分享你的反馈。 | 

## 侧边栏

| English           | 简体中文 |
| ----------------- | -------- |
| Reset Thread      | 重开对话 | 
| Dark Mode         | 深色主题 | 
| Light Mode        | 浅色主题 | 
| OpenAI Discord    | 加入社群 | 
| Learn More        | 了解更多 | 
| No login required | 无需登录 | 

## 主页

| English           | 简体中文 |
| ----------------- | -------- |
| ChatGPT           | ChatGPT  | 
| If no answer, try more times     | 如果没有答案，多试几次 | 
| Examples          | 提问案例   | 
| Capabilities      | 功能特性   | 
| Limitations       | 使用限制   | 
| "Explain quantum computing in simple terms"            | 讲解一下什么是量子计算  | 
| "Got any creative ideas for a 10year old's birthday?"  | 准备为10岁的孩子过生日，有什么创意的想法吗 |
| "How do i make an HTTP request in Javascript?"         | 如何用 JavaScript 发送 HTTP 请求  |
| Remembers what user said earlier in the conversation.  | 记住用户在本次对话说过的内容 | 
| Allows user to provide follow-up corrections.          | 允许用户在下文提供后续内容的更正 | 
| Trained to decline inappropriate requests.             | 接受过专业的语言训练，会合理拒绝不正当的请求 | 
| May occasionally generate incorrect information.       | 可能会产生不准确的信息 | 
| May occasionally produce harmful instructions or biased content. | 可能会产生带有偏见或违反安全准则的内容 | 
| Limited knowledge of world and events after 2021.      | 对2021年以后的世界了解有限。 | 
| DISCLAIMER: https://chat.bygpt.com is a non-profit ChatGPT reverse proxy site, with no affiliation with OpenAI, and is intended for people with restricted access to areas by OpenAI | 免责声明：https://chat.bygpt.com 是一个非营利性的 ChatGPT 反向代理网站，与 OpenAI 没有任何关系，目的仅用于那些被 OpenAI 限制访问的地区提供服务。 |

## 异常错误

| English           | 简体中文 |
| ----------------- | -------- |
| The request for the current account is too frequent, please try to refresh the page to change to a new account. | 当前请求过于频繁，请尝试刷新页面 | 
| The request for the current account is too frequent, please try to refresh the page to change to a new account. | 当前账号请求过于频繁，请刷新页面重新分配新的账号 | 
| Conversation not found | 对话状态已过期，请刷新页面重新开始对话 |
| An error occurred. Either the engine you requested does not exist or there was another issue processing your request. If this issue persists please contact us through our help center at help.openai.com. | 处理请求时遇到了错误。如果这个问题持续发生，请联系网站管理员获得更多帮助。

## 编辑提问

| English         | 简体中文    |
| --------------- | ----------- |
| Save & Submit   | 保存并提交  | 
| Cancel          | 取消        | 

## 评价弹窗

| English                                | 简体中文 |
| -------------------------------------- | --------------- |
| Provide additional feedback            | 补充更多反馈    | 
| What would the ideal answer have been? | 你认为更合适的回应是什么？ | 
| Submit feedback                        | 提交反馈 | 

## 其他建议

建议标题将 `如果没有答案，多试几次` 跟 `ChatGPT` 独立分开，放在标题下方的灰色小字提示会更好

**Comment by wsdo** [comment]
优秀
